# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /feedstock/recipe, last modified Thu Feb  8 01:26:06 2024
# ------------------------------------------------

package:
  name: requests
  version: 2.31.0
source:
  sha256: 942c5a758f98d790eaed1a29cb6eefc7ffb0d1cf7af05c3d2791656dbd6ad1e1
  url: https://pypi.io/packages/source/r/requests/requests-2.31.0.tar.gz
build:
  number: '1'
  script: /croot/requests_1707355572290/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py312h06a4308_1
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2023.12.12 h06a4308_0
    - expat 2.5.0 h6a678d5_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.4 h6a678d5_0
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.13 h7f8727e_0
    - pip 23.3.1 py312h06a4308_0
    - python 3.12.1 h996f2a0_0
    - readline 8.2 h5eee18b_0
    - setuptools 68.2.2 py312h06a4308_0
    - sqlite 3.41.2 h5eee18b_0
    - tk 8.6.12 h1ccaba5_0
    - tzdata 2023d h04d1e81_0
    - wheel 0.41.2 py312h06a4308_0
    - xz 5.4.5 h5eee18b_0
    - zlib 1.2.13 h5eee18b_0
  run:
    - certifi >=2017.4.17
    - charset-normalizer >=2,<4
    - idna >=2.5,<4
    - python >=3.12,<3.13.0a0
    - urllib3 >=1.21.1,<3
  run_constrained:
    - chardet >=3.0.2,<6
    - pysocks >=1.5.6,!=1.5.7
test:
  commands:
    - pip check
    - conda create -v --dry-run -n requests-test numpy
  imports:
    - requests
  requires:
    - conda
    - pip
about:
  description: 'Requests is the only Non-GMO HTTP library for Python, safe for human

    consumption.

    '
  dev_url: https://github.com/psf/requests
  doc_url: https://requests.readthedocs.io/
  home: https://requests.readthedocs.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "Requests is an elegant and simple HTTP library for Python, built with\
    \ \u2665."
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: cdde0db8-1e92-4f39-a705-d5c85a28a72a
  recipe-maintainers:
    - carlodri
    - jakirkham
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - sigmavirus24
  remote_url: git@github.com:AnacondaRecipes/requests-feedstock.git
  sha: e4711e7df19e871543f7a4daa82ac62411677ff2
