# This file created by conda-build 3.21.8
# ------------------------------------------------

package:
  name: reproc-cpp
  version: 14.2.4
source:
  - patches: null
    sha256: 55c780f7faa5c8cabd83ebbb84b68e5e0e09732de70a129f6b3c801e905415dd
    url: https://github.com/DaanDeMeyer/reproc/archive/v14.2.4.tar.gz
build:
  number: 1
  run_exports:
    - reproc-cpp >=14.2,<15.0a0
  string: h295c915_1
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.35.1 h27ae35d_9
    - binutils_linux-64 2.35.1 h454624a_30
    - bzip2 1.0.8 h7b6447c_0
    - c-ares 1.18.1 h7f8727e_0
    - ca-certificates 2022.2.1 h06a4308_0
    - cmake 3.22.1 h1fce559_0
    - expat 2.4.4 h295c915_0
    - gcc_impl_linux-64 7.5.0 h7105cf2_17
    - gcc_linux-64 7.5.0 h8f34230_30
    - gxx_impl_linux-64 7.5.0 h0a5bf11_17
    - gxx_linux-64 7.5.0 hffc177d_30
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - krb5 1.19.2 hac12032_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libcurl 7.80.0 h0b77cf5_0
    - libedit 3.1.20210910 h7f8727e_0
    - libev 4.33 h7f8727e_1
    - libffi 3.3 he6710b0_2
    - libgcc-devel_linux-64 7.5.0 hbbeae57_17
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libnghttp2 1.46.0 hce63b2e_0
    - libssh2 1.9.0 h1ba5d50_1
    - libstdcxx-devel_linux-64 7.5.0 hf0c5c8d_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuuid 1.0.3 h7f8727e_2
    - libuv 1.40.0 h7b6447c_0
    - lz4-c 1.9.3 h295c915_1
    - ncurses 6.3 h7f8727e_2
    - ninja 1.10.2 py310hd09550d_3
    - openssl 1.1.1m h7f8727e_0
    - python 3.10.0 h12debd9_5
    - readline 8.1.2 h7f8727e_1
    - rhash 1.4.1 h3c74f83_1
    - sqlite 3.38.0 hc218d9a_0
    - sysroot_linux-64 2.17 h57e8cba_10
    - tk 8.6.11 h1ccaba5_0
    - tzdata 2021e hda174b7_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7f8727e_4
    - zstd 1.5.0 ha4553b6_1
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - reproc 14.2.4 h295c915_1
  run:
    - libgcc-ng >=7.5.0
    - libstdcxx-ng >=7.5.0
    - reproc 14.2.4 h295c915_1
test:
  commands:
    - test -f ${PREFIX}/include/reproc++/reproc.hpp
    - test -f ${PREFIX}/lib/libreproc++${SHLIB_EXT}
    - test -f ${PREFIX}/lib/cmake/reproc++/reproc++-config.cmake
    - test ! -f ${PREFIX}/lib/libreproc++.a
about:
  dev_url: https://github.com/DaanDeMeyer/reproc
  doc_src_url: https://github.com/DaanDeMeyer/reproc
  doc_url: https://github.com/DaanDeMeyer/reproc#reproc
  home: https://github.com/DaanDeMeyer/reproc
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: reproc (Redirected Process) is a cross-platform C/C++ library that simplifies
    starting, stopping and communicating with external programs.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - DaanDeMeyer
    - wolfv
